### ISSUE TITLE
Missing "Category" in create goal  - POST

### ISSUE THREAD

**Issue by ismael-henrique-dev** [ciringa/Control_Finance-V2-API#3]
![Captura de tela de 2024-09-26 20-44-13](https://github.com/user-attachments/assets/f468a4ac-93f0-4155-9a8f-3c35b557ae8e)
![image](https://github.com/user-attachments/assets/b86a8649-96fd-4666-a47a-7a96802726dc)

**Comment by ciringa** [comment]
Não adicionei pq não faz sentido
