### ISSUE TITLE
The "AccountTitle" attribute is missing in the return from creating a transaction (this is so that I can directly update the transaction). - /transaction/create

### ISSUE THREAD

**Issue by ismael-henrique-dev** [ciringa/Control_Finance-V2-API#4]
[
![Captura de tela de 2024-09-27 19-16-37](https://github.com/user-attachments/assets/e34347f3-0d3e-44ae-9c9d-3aeebcbcbea4)
](url)

**Comment by ciringa** [comment]
AccountTitle is getting returned you're just using the wrong route. Try using GET /transactions
