### ISSUE TITLE
A rota de atiualizar a meta não está funcionando,

### ISSUE THREAD

**Issue by ismael-henrique-dev** [ciringa/Control_Finance-V2-API#7]
[
![Captura de tela de 2024-09-29 14-35-40](https://github.com/user-attachments/assets/ae2f3710-0633-4872-9ceb-3220e6218a84)
](url)

**Comment by ciringa** [comment]
it is indeed working. fixed in the last commit 

![Imagem do WhatsApp de 2024-10-02 à(s) 21 58 19_5ded140c](https://github.com/user-attachments/assets/ca2cd107-5e4c-4614-ab13-d46bd2a68052)
